site_name: MFEM
site_url: http://mfem.org
docs_dir: 'src'

markdown_extensions:
- extra  # allow markdown in <div markdown="1">
- fenced_code  # GitHub style code blocks, e.g. ```python, see http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html for a list of languages

repo_url: https://github.com/mfem/mfem
remote_name: origin

nav:
- Home: index.md
- Features: features.md
- Examples: examples.md
- Documentation:
  - '_News': news.md   # pages starting with '_' are hidden from the menu
  - 'Building MFEM': building.md
  - 'Serial Tutorial': serial-tutorial.md
  - 'Parallel Tutorial': parallel-tutorial.md
  - 'Finite Elements': fem.md
  - '_Primal and Dual Vectors': pri-dual-vec.md
  - '_Bilinear Form Integrators': bilininteg.md
  - '_Linear Form Integrators': lininteg.md
  - '_Linear Interpolators': lininterp.md
  - '_Boundary Conditions': fem_bc.md
  - 'Electromagnetics': electromagnetics.md
  - 'Meshing': meshing.md
  - '_Mesh Formats': mesh-formats.md
  - '_Mesh Format v1.x': mesh-format-v1.x.md
  - 'Performance': performance.md
  - '_Code Overview': code-overview.md
  - 'Tools': tools.md
  - 'Toys': toys.md
  - 'Publications': publications.md
  - 'About': about.md
- Gallery: gallery.md
- Download: download.md

theme:
  name: mkdocs  # required. Can be anything as long as custom_dir is set correctly below
  custom_dir: template

extra:
  include_next_prev: false  # turn off next/previous buttons

google_analytics: ['UA-101697-3', 'mfem.org']
